name: ci-sonarcloud

on:
  pull_request:
    branches:
      - develop

jobs: 
  run-ci: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 14.x
      - run: npm install
      - run: npm run test
